<?PHP

/** DO NOT EDIT THIS FILE - GENERATE WITH CLASS OPTIONS **/

$op_set_offline = "0";
$op_set_offline_message = "<p>das Game ist Offline</p>";
$op_impressum = "<p><strong><br /><br /><span style=\"color: #ff6600;\">Die Litotex OpenSource Browsergame wurde entwickelt vom Litotex Team.</span><br /><br /></strong>F&uuml;r Fragen, Anregungen lohnt sich ein Besuch des <a title=\"Litotex Forum\" href=\"http://www.litotex.de\" target=\"_blank\">Litotex Forums.</a></p>\r\n<p>Diese Software ist nich als fertiges Browsergame gedacht, sondern vielmehr als Vorlage f&uuml;r die eigenen Ideen und W&uuml;nsche.<br /><br /><strong>Besonderen Dank gilt allen Mitwirkenden:<br /></strong></p>\r\n<ul>\r\n<li><strong>gh1234</strong></li>\r\n<li><strong>KiraYamato</strong></li>\r\n<li><strong>ofliii</strong></li>\r\n<li><strong>SnooP</strong></li>\r\n<li><strong>Sonorc</strong></li>\r\n<li><strong>Tungdal<br /><br /></strong></li>\r\n</ul>\r\n<p>Ein gro&szlig;er Dank geht auch an die Foren-Community, welche uns mit Ideen, Fehlerfindung und jede menge guter Laune immer wieder dazu Motivierte noch einen Schritt weiter zu gehen.<strong><br /><br />Und nicht zu vergessen, die Freunde/in, Eltern, oder Familienangeh&ouml;rigen, die viele Stunden auf uns verzichten mussten ;)<br /></strong></p>";
$op_set_gamename = "LITOTEX OpenSource Browsergame";
$op_set_game_url = "http://www.freebg.de";
$op_admin_email = "info@freebg.de";
$op_support_email = "info@freebg.de";
$op_max_players = "11";
$op_set_store_max = "1200";
$op_store_mulit = "12";
$op_enhance_country = "60";
$op_min_c_size = "500";
$op_max_c_size = "1000";
$op_res_reload_time = "3600";
$op_set_n_res1 = "Getreide";
$op_set_n_res2 = "Ziegel";
$op_set_n_res3 = "Münzen";
$op_set_n_res4 = "Waffen";
$op_mup_res1 = "100";
$op_mup_res2 = "100";
$op_mup_res3 = "100";
$op_mup_res4 = "100";
$op_reg_res1 = "1000";
$op_reg_res2 = "1000";
$op_reg_res3 = "1000";
$op_reg_res4 = "1000";
$op_set_res1 = "1000";
$op_set_res2 = "100";
$op_set_res3 = "100";
$op_set_res4 = "100";
$op_battle_countdown_time = "6000";
$op_battle_countdown_time2 = "60";
$op_land_duration = "1";
$op_max_lands = "5";
$op_max_ali_members = "10";
$op_credit_demolition = "25";
$op_set_game_author = "FreeBG TEAM";
$op_credit_cancel = "50";
$op_use_badwords = "1";
$op_res_reload_type = "0";
$op_noob_points = "100";
$op_noob_time = "3";
$op_battle_trace = "1";
$op_res_steal = "50";
$op_send_html_mail = "0";
$op_use_ftp_mode="0";


?>