<?PHP
/*
************************************************************
Litotex Browsergame - Engine
http://www.Litotex.de
http://www.freebg.de

Copyright (c) 2008 FreeBG Team
************************************************************
Hinweis:
Diese Software ist urheberrechtlich geschützt.

Für jegliche Fehler oder Schäden, die durch diese Software
auftreten könnten, übernimmt der Autor keine Haftung.

Alle Copyright - Hinweise innerhalb dieser Datei
dürfen WEDER entfernt, NOCH verändert werden.
************************************************************
Released under the GNU General Public License
************************************************************

*/
class option {


	var $dir = "";


	function option($dir) {
		$this->dir = $dir;
	}


	function write() {
		global $db, $n, $serverid;
		if ($serverid==""){
			$serverid=0;
		}
		$fp = fopen($this->dir."options.php", "w");
		$fw = fwrite($fp, "<?PHP\n\n/** DO NOT EDIT THIS FILE - GENERATE WITH CLASS OPTIONS **/\n\n");
		fclose($fp);

		$result=$db->query("SELECT * FROM cc".$n."_menu_admin_opt");
		while($row=$db->fetch_Array($result)) {
			$fp = fopen($this->dir."options.php", "a+");
			$new_var=mysql_real_escape_string($row['value']);
			$fw = fwrite($fp, "\$".$row['varname']." = \"".$new_var."\";\n");
			fclose($fp);
		}
		$fp = fopen($this->dir."options.php", "a+");
		$fw = fwrite($fp, "\n\n?>");
		fclose($fp);
	}
}

?>
